### PR TITLE
bug-fix(hello.any)  Fix a bug: Some Python versions have no output #1

### PR DESCRIPTION
**Pull request by fexcode**
Fix # 1 Error
C. Python language runs normally, BF not tested
(Tested）

### CODE REVIEW

**Comment by fexcode** [comment]
Do not use code # 1, as there is a Python version conflict bug. This PR code solves this bug.

**Comment by fexcode** [comment]
## Why don't we use `import __hello__ ` ?
Because in Python 3.11 the and modules no longer print the text when they are imported. You now have to call the module’s main method to get the same effect: `__hello__` `__phello__`
(See https://blog.pecar.me/import-hello for details)

**Comment by fexcode** [comment]
I have added the test folder,
but I think that the '.gitignore' file may have some usage in the future
so I have not deleted it

**Comment by BaiChuanByte** [comment]
Why place files in folder test? Do I have to change all the files when updating?

**Comment by fexcode** [comment]
DELETE THE TEST FOLDER!!!!!

**Comment by fexcode** [comment]
test => test-cache
(To avoid user confusion)

**Pull request merged**
